'use client';

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from 'react';

/**
 * Session store — fully client-side. No persistent server database.
 *
 * Memory model:
 *   - Active session id is a fresh random string, regenerated by `newSession()`.
 *   - All turns are kept in memory only; refreshing the browser wipes them.
 *   - A lightweight session LIST (id, title, messageCount, preview) is held
 *     in client memory so the sidebar can render history without a server.
 *   - `persistTurn` only updates in-memory state; it intentionally does not
 *     touch any DB.
 *
 * This keeps OMNI-AI stateless on the server side, so it deploys to Vercel
 * with zero database provisioning.
 */

export interface UiMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
  model?: string;
  latencyMs?: number;
  tokens?: number;
}

export interface SessionSummary {
  id: string;
  title: string;
  updatedAt: number;
  messageCount: number;
  preview: string | null;
}

interface SessionStoreValue {
  sessions: SessionSummary[];
  activeSessionId: string;
  messages: UiMessage[];
  loading: boolean;
  /** Derived — total chars across messages divided by 4. */
  tokenEstimate: number;

  /** Wipe messages and mint a new random session id. Always succeeds. */
  newSession: () => string;
  /** Switch to an existing session. Wipes in-memory messages since we
   * are stateless and don't fetch prior turns from any database. */
  selectSession: (id: string) => void;
  /** Replace messages with the given list (used by selectSession). */
  loadMessages: (msgs: UiMessage[]) => void;
  /** Append a user/assistant turn pair into the active session. */
  persistTurn: (args: {
    userContent: string;
    assistantContent: string;
    metrics?: { model?: string; provider?: string; latencyMs?: number; tokens?: number };
  }) => void;
  /** Remove a session from the in-memory list. */
  removeSession: (id: string) => void;
  /** Drop the active session's messages but keep the id. */
  resetActiveMessages: () => void;
}

const SessionContext = createContext<SessionStoreValue | null>(null);

function mintId(): string {
  // Pure client-only generator; Math.random is fine — sessions never leave the browser.
  return `ses_${Math.random().toString(36).slice(2, 10)}${Date.now().toString(36).slice(-4)}`;
}

function deriveTitle(text: string): string {
  const trimmed = text.trim().replace(/\s+/g, ' ');
  if (!trimmed) return 'New Chat';
  return trimmed.length > 60 ? `${trimmed.slice(0, 57)}…` : trimmed;
}

function previewOf(text: string): string {
  const trimmed = text.trim().replace(/\s+/g, ' ');
  if (!trimmed) return '';
  return trimmed.length > 80 ? `${trimmed.slice(0, 77)}…` : trimmed;
}

export function SessionProvider({ children }: { children: ReactNode }) {
  // Stable per-mount session id. We DO NOT regenerate on every render.
  const [activeSessionId, setActiveSessionId] = useState<string>(() => mintId());
  const [sessions, setSessions] = useState<SessionSummary[]>(() => [
    { id: activeSessionId, title: 'New Chat', updatedAt: Date.now(), messageCount: 0, preview: null },
  ]);
  const [messages, setMessages] = useState<UiMessage[]>([]);
  const [loading, setLoading] = useState(false);
  const mountedRef = useRef(true);

  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
    };
  }, []);

  const newSession = useCallback((): string => {
    const id = mintId();
    if (!mountedRef.current) return id;
    setSessions((prev) => {
      if (prev.length === 0) {
        return [{ id, title: 'New Chat', updatedAt: Date.now(), messageCount: 0, preview: null }];
      }
      const exists = prev.some((s) => s.id === id);
      if (exists) return prev;
      return [
        { id, title: 'New Chat', updatedAt: Date.now(), messageCount: 0, preview: null },
        ...prev,
      ];
    });
    setActiveSessionId(id);
    setMessages([]);
    return id;
  }, []);

  const loadMessages = useCallback((msgs: UiMessage[]) => {
    setMessages(msgs);
  }, []);

  const selectSession = useCallback((id: string) => {
    setActiveSessionId(id);
    // Stateless — switching sessions wipes the active canvas (no DB to load from).
    setMessages([]);
  }, []);

  const persistTurn = useCallback<SessionStoreValue['persistTurn']>(
    (args) => {
      const ts = Date.now();
      const userMsg: UiMessage = {
        id: `m_${Math.random().toString(36).slice(2, 10)}`,
        role: 'user',
        content: args.userContent,
        timestamp: ts,
      };
      const assistantMsg: UiMessage = {
        id: `m_${Math.random().toString(36).slice(2, 10)}`,
        role: 'assistant',
        content: args.assistantContent,
        timestamp: ts,
        model: args.metrics?.model,
        latencyMs: args.metrics?.latencyMs,
        tokens: args.metrics?.tokens,
      };
      setMessages((prev) => [...prev, userMsg, assistantMsg]);
      setSessions((prev) => {
        const idx = prev.findIndex((s) => s.id === activeSessionId);
        const summary: SessionSummary = {
          id: activeSessionId,
          title: idx >= 0 ? prev[idx].title : deriveTitle(args.userContent),
          updatedAt: ts,
          messageCount: (idx >= 0 ? prev[idx].messageCount : 0) + 2,
          preview: previewOf(args.assistantContent),
        };
        if (idx >= 0) {
          // First user message renames the session.
          if (prev[idx].title === 'New Chat') {
            summary.title = deriveTitle(args.userContent);
          }
          const next = prev.slice();
          next[idx] = summary;
          return next;
        }
        return [summary, ...prev];
      });
    },
    [activeSessionId],
  );

  const removeSession = useCallback(
    (id: string) => {
      setSessions((prev) => {
        const filtered = prev.filter((s) => s.id !== id);
        // Don't leave the list empty — always keep at least one session marker.
        if (filtered.length === 0) {
          return [
            { id: activeSessionId, title: 'New Chat', updatedAt: Date.now(), messageCount: 0, preview: null },
          ];
        }
        return filtered;
      });
      // If we deleted the active session, mint a fresh one so the user
      // can keep chatting without manually clicking [+ NEW CHAT].
      if (id === activeSessionId) {
        const fresh = mintId();
        setActiveSessionId(fresh);
        setMessages([]);
      }
    },
    [activeSessionId],
  );

  const resetActiveMessages = useCallback(() => {
    setMessages([]);
  }, []);

  const tokenEstimate = useMemo(
    () => Math.round(messages.reduce((acc, m) => acc + (m.content?.length ?? 0), 0) / 4),
    [messages],
  );

  const value = useMemo<SessionStoreValue>(
    () => ({
      sessions,
      activeSessionId,
      messages,
      loading,
      tokenEstimate,
      newSession,
      selectSession,
      loadMessages,
      persistTurn,
      removeSession,
      resetActiveMessages,
    }),
    [sessions, activeSessionId, messages, loading, tokenEstimate, newSession, selectSession, loadMessages, persistTurn, removeSession, resetActiveMessages],
  );

  return <SessionContext.Provider value={value}>{children}</SessionContext.Provider>;
}

export function useSessionStore(): SessionStoreValue {
  const ctx = useContext(SessionContext);
  if (!ctx) throw new Error('useSessionStore must be used within SessionProvider');
  return ctx;
}